/**
 * EmpresaIQ — SQLite Database Layer (browser, via sql.js + IndexedDB)
 *
 * Schema:
 *   admin_keys  — keys generated by admin (key, label, created_at, revoked)
 *   users       — registered users (key, name, registered_at)
 *   progress    — course lesson completion (user_key, lesson_slug, completed_at)
 *
 * Persistence: the SQLite binary is saved to IndexedDB on every write.
 * Migration: on first run, existing localStorage data is imported automatically.
 */

// ── IndexedDB helpers ─────────────────────────────────────────────────────────

const IDB_NAME = 'empresaiq_sqlite';
const IDB_STORE = 'db';
const IDB_KEY = 'data';
const IDB_VERSION = 1;

function openIDB(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(IDB_NAME, IDB_VERSION);
    req.onupgradeneeded = () => req.result.createObjectStore(IDB_STORE);
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}

async function loadFromIDB(): Promise<Uint8Array | null> {
  try {
    const idb = await openIDB();
    return new Promise(resolve => {
      const req = idb.transaction(IDB_STORE).objectStore(IDB_STORE).get(IDB_KEY);
      req.onsuccess = () => resolve(req.result ?? null);
      req.onerror = () => resolve(null);
    });
  } catch { return null; }
}

async function saveToIDB(data: Uint8Array): Promise<void> {
  try {
    const idb = await openIDB();
    await new Promise<void>(resolve => {
      const tx = idb.transaction(IDB_STORE, 'readwrite');
      tx.objectStore(IDB_STORE).put(data, IDB_KEY);
      tx.oncomplete = () => resolve();
      tx.onerror = () => resolve();
    });
  } catch { /* ignore */ }
}

// ── Schema ────────────────────────────────────────────────────────────────────

function createSchema(db: any): void {
  db.run(`
    CREATE TABLE IF NOT EXISTS admin_keys (
      id         INTEGER PRIMARY KEY AUTOINCREMENT,
      key        TEXT    UNIQUE NOT NULL,
      label      TEXT    DEFAULT '',
      created_at TEXT    NOT NULL,
      revoked    INTEGER DEFAULT 0
    )
  `);
  db.run(`
    CREATE TABLE IF NOT EXISTS users (
      id            INTEGER PRIMARY KEY AUTOINCREMENT,
      key           TEXT UNIQUE NOT NULL,
      name          TEXT DEFAULT '',
      registered_at TEXT NOT NULL
    )
  `);
  db.run(`
    CREATE TABLE IF NOT EXISTS progress (
      id           INTEGER PRIMARY KEY AUTOINCREMENT,
      user_key     TEXT NOT NULL,
      lesson_slug  TEXT NOT NULL,
      completed_at TEXT NOT NULL,
      UNIQUE(user_key, lesson_slug)
    )
  `);
}

// ── Migration from localStorage ───────────────────────────────────────────────

function migrateLocalStorage(db: any): void {
  if (typeof window === 'undefined') return;
  if (localStorage.getItem('empresaiq_db_migrated')) return;

  try {
    // Admin keys
    const rawKeys = localStorage.getItem('empresaiq_admin_generated_keys');
    if (rawKeys) {
      const records: Array<{ key: string; label: string; createdAt: string; revoked: boolean }> =
        JSON.parse(rawKeys);
      records.forEach(r => {
        try {
          db.run(
            'INSERT OR IGNORE INTO admin_keys (key, label, created_at, revoked) VALUES (?,?,?,?)',
            [r.key, r.label ?? '', r.createdAt ?? new Date().toISOString(), r.revoked ? 1 : 0],
          );
        } catch { /* skip duplicates */ }
      });
    }

    // User
    const userKey = localStorage.getItem('empresaiq_user_key');
    const userName = localStorage.getItem('empresaiq_user_name');
    if (userKey) {
      try {
        db.run(
          'INSERT OR IGNORE INTO users (key, name, registered_at) VALUES (?,?,?)',
          [userKey, userName ?? '', new Date().toISOString()],
        );
      } catch { /* skip */ }
    }

    // Progress
    const rawProgress = localStorage.getItem('empresaiq_curso_progress');
    if (rawProgress && userKey) {
      const slugs: string[] = JSON.parse(rawProgress);
      slugs.forEach(slug => {
        try {
          db.run(
            'INSERT OR IGNORE INTO progress (user_key, lesson_slug, completed_at) VALUES (?,?,?)',
            [userKey, slug, new Date().toISOString()],
          );
        } catch { /* skip */ }
      });
    }

    localStorage.setItem('empresaiq_db_migrated', '1');
  } catch { /* ignore migration errors */ }
}

// ── Singleton ─────────────────────────────────────────────────────────────────

let _db: any = null;
let _initPromise: Promise<any> | null = null;

export async function getDB(): Promise<any> {
  if (_db) return _db;
  if (_initPromise) return _initPromise;

  _initPromise = (async () => {
    // Dynamic import avoids SSR errors
    const { default: initSqlJs } = await import('sql.js');
    const SQL = await initSqlJs({ locateFile: (f: string) => `/sqljs/${f}?v=1` });

    const saved = await loadFromIDB();
    _db = saved ? new SQL.Database(saved) : new SQL.Database();

    createSchema(_db);
    migrateLocalStorage(_db);
    await saveToIDB(_db.export());

    return _db;
  })();

  return _initPromise;
}

/** Export the current DB as a downloadable .sqlite file */
export function exportDB(): void {
  if (!_db) return;
  const data = _db.export();
  const blob = new Blob([data], { type: 'application/octet-stream' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `empresaiq-${new Date().toISOString().slice(0, 10)}.sqlite`;
  a.click();
  URL.revokeObjectURL(url);
}

async function persist(): Promise<void> {
  if (_db) await saveToIDB(_db.export());
}

function toRows<T>(result: Array<{ columns: string[]; values: any[][] }>): T[] {
  if (!result.length) return [];
  const { columns, values } = result[0];
  return values.map(row => {
    const obj: any = {};
    columns.forEach((c, i) => (obj[c] = row[i]));
    return obj as T;
  });
}

// ── Admin Keys API ────────────────────────────────────────────────────────────

export interface DBKeyRecord {
  id: number;
  key: string;
  label: string;
  created_at: string;
  revoked: boolean;
}

export async function dbGetAllKeys(): Promise<DBKeyRecord[]> {
  const db = await getDB();
  const rows = toRows<any>(db.exec(
    'SELECT id, key, label, created_at, revoked FROM admin_keys ORDER BY id DESC',
  ));
  return rows.map(r => ({ ...r, revoked: r.revoked === 1 }));
}

export async function dbInsertKey(key: string, label: string): Promise<void> {
  const db = await getDB();
  db.run(
    'INSERT OR IGNORE INTO admin_keys (key, label, created_at, revoked) VALUES (?,?,?,0)',
    [key, label, new Date().toISOString()],
  );
  await persist();
}

export async function dbRevokeKey(key: string): Promise<void> {
  const db = await getDB();
  db.run('UPDATE admin_keys SET revoked = 1 WHERE key = ?', [key]);
  await persist();
}

export async function dbDeleteKey(key: string): Promise<void> {
  const db = await getDB();
  db.run('DELETE FROM admin_keys WHERE key = ?', [key]);
  await persist();
}

export async function dbGetKeyStat(): Promise<{ total: number; active: number; revoked: number }> {
  const db = await getDB();
  const rows = toRows<any>(db.exec(`
    SELECT
      COUNT(*)                        AS total,
      SUM(CASE WHEN revoked=0 THEN 1 ELSE 0 END) AS active,
      SUM(CASE WHEN revoked=1 THEN 1 ELSE 0 END) AS revoked
    FROM admin_keys
  `));
  const r = rows[0] ?? { total: 0, active: 0, revoked: 0 };
  return { total: r.total ?? 0, active: r.active ?? 0, revoked: r.revoked ?? 0 };
}

// ── Users API ─────────────────────────────────────────────────────────────────

export async function dbUpsertUser(key: string, name: string): Promise<void> {
  const db = await getDB();
  db.run(
    `INSERT INTO users (key, name, registered_at) VALUES (?,?,?)
     ON CONFLICT(key) DO UPDATE SET name = excluded.name`,
    [key, name, new Date().toISOString()],
  );
  await persist();
}

export async function dbGetUser(key: string): Promise<{ name: string } | null> {
  const db = await getDB();
  const rows = toRows<{ name: string }>(db.exec('SELECT name FROM users WHERE key = ?', [key]));
  return rows[0] ?? null;
}

// ── Progress API ──────────────────────────────────────────────────────────────

export async function dbGetProgress(userKey: string): Promise<string[]> {
  if (!userKey) return [];
  const db = await getDB();
  const rows = toRows<{ lesson_slug: string }>(
    db.exec('SELECT lesson_slug FROM progress WHERE user_key = ?', [userKey]),
  );
  return rows.map(r => r.lesson_slug);
}

export async function dbMarkComplete(userKey: string, slug: string): Promise<void> {
  const db = await getDB();
  db.run(
    'INSERT OR IGNORE INTO progress (user_key, lesson_slug, completed_at) VALUES (?,?,?)',
    [userKey, slug, new Date().toISOString()],
  );
  await persist();
}

export async function dbGetProgressCount(userKey: string): Promise<number> {
  if (!userKey) return 0;
  const db = await getDB();
  const rows = toRows<{ cnt: number }>(
    db.exec('SELECT COUNT(*) AS cnt FROM progress WHERE user_key = ?', [userKey]),
  );
  return rows[0]?.cnt ?? 0;
}
